name: Docker Run Action Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker action and set output for testing
        uses: ./
        id: run-docker
        with:
          image: docker:20.10.3
          run: |
            echo "::set-output name=docker-version::`echo $DOCKER_VERSION`"
      - name: Test the output
        uses: actions/github-script@v3
        with:
          script: |
            const dockerVersion = '${{ steps.run-docker.outputs.docker-version }}';
            if (dockerVersion !== '20.10.3') {
              core.setFailed(`Smoke Test Failed`);
            }
  volume-mount-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create File to be mounted
        run: echo "some text" > someFile
      - name: Run docker action with mounted workspace
        uses: ./
        id: run-docker
        with:
          image: docker
          run: |
            echo "::set-output name=file-contents::`cat someFile`"
      - name: Check if file contents match
        uses: actions/github-script@v3
        with:
          script: |
            const fileContents = '${{ steps.run-docker.outputs.file-contents }}';
            if (fileContents !== 'some text') {
              core.setFailed(`Unable to mount workspace volume`);
            }
  clickable-test:
    strategy:
      fail-fast: false
      matrix:
         arch: [armhf, arm64, amd64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run docker and test clickable
        env:
            ARCH: ${{ matrix.arch }}
        uses: ./
        id: run-docker
        with:
          image: clickable/ci-16.04-${ARCH}
          run: |
            clickable --help
